spring.application.name=OrbitalSync
spring.datasource.url=jdbc:mysql://localhost:3306/orbitalsync
spring.datasource.username=root
spring.datasource.password=D314314@ml

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true